{
 "title": "Trades Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "symbol",
    "label": "Symbol",
    "query": "SELECT DISTINCT symbol FROM trades"
   },
   { "name": "interval", "label": "Timeframe", "query": "1m,5m" }
  ]
 },
 "panels": [
  {
   "title": "${symbol} Price",
   "type": "candlestick",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(time/1000000, $interval),\n  first(price, time) as \"open\",\n  last(price, time) as \"close\",\n  min(price) as \"low\",\n  max(price) as \"high\",\n  sum(quantity) as \"volume\"\nFROM trades\nWHERE\n  symbol = '${symbol}' and $__unixEpochFilter(time/1000000)\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "${symbol} Last Price",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\ntime,\n  price\nFROM trades\nWHERE\n  symbol = '${symbol}'\nORDER BY time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "${symbol} Last trades",
   "type": "table",
   "gridPos": { "h": 18, "w": 7, "x": 15, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  time/1000000 as \"time\",\n  price,\n  quantity,\n  is_buy::int\nFROM trades\nWHERE\n  symbol = '${symbol}' and $__unixEpochFilter(time/1000000)\nORDER BY time DESC\nLIMIT 30"
    }
   ]
  },
  {
   "title": "${symbol} Volume Delta",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(time/1000000, $interval),\n  SUM(CASE WHEN is_buy THEN quantity ELSE 0 END) - SUM(CASE WHEN not is_buy THEN quantity ELSE 0 END) as \"delta\"\nFROM trades\nWHERE\n  symbol = '${symbol}' and $__unixEpochFilter(time/1000000)\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "${symbol} Cumulative Volume Delta",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  s.time,\n  SUM(SUM(s.delta)) OVER(ORDER BY s.time)\nFROM (\nSELECT\n  $__unixEpochGroupAlias(time/1000000, $interval),\n  SUM(CASE WHEN is_buy THEN quantity ELSE 0 END) - SUM(CASE WHEN not is_buy THEN quantity ELSE 0 END) as \"delta\"\nFROM trades\nWHERE\n  symbol = '${symbol}' and $__unixEpochFilter(time/1000000)\nGROUP BY 1\nORDER BY 1\n) as s\nGROUP BY 1, time\nORDER BY 1\n"
    }
   ]
  }
 ]
}